import { Job } from './filters';

// Define job data as a constant array with many more jobs for proper pagination
const JOBS_DATA: Job[] = [
  {
    "id": "jb_0001",
    "title": "Frontend Developer",
    "company": "Acme Labs",
    "location": "Accra, GH",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 6000, "max": 9000, "currency": "GHS", "period": "month" },
    "experience": "Junior",
    "postedAt": "2025-01-18",
    "tags": ["React", "TypeScript", "Next.js"],
    "description": "We're looking for a passionate Frontend Developer to join our growing team. You'll work on building beautiful, responsive user interfaces and contribute to our product development.",
    "responsibilities": ["Build responsive UI components", "Write clean, maintainable code", "Collaborate with design and backend teams", "Write unit tests"],
    "requirements": ["1+ year experience with React", "Proficiency in TypeScript", "Knowledge of modern CSS and responsive design", "Experience with Git"],
    "benefits": ["Health insurance", "Remote work stipend", "Learning budget", "Flexible hours"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0002",
    "title": "Senior Backend Engineer",
    "company": "TechCorp Solutions",
    "location": "Lagos, NG",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 12000, "max": 18000, "currency": "NGN", "period": "month" },
    "experience": "Senior",
    "postedAt": "2025-01-17",
    "tags": ["Node.js", "Python", "PostgreSQL", "AWS"],
    "description": "Join our engineering team to build scalable backend services and APIs. You'll lead technical decisions and mentor junior developers.",
    "responsibilities": ["Design and implement backend services", "Optimize database performance", "Lead code reviews", "Mentor junior developers"],
    "requirements": ["5+ years backend development", "Expert in Node.js or Python", "Experience with cloud platforms", "Strong system design skills"],
    "benefits": ["Competitive salary", "Health coverage", "Stock options", "Conference attendance"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0003",
    "title": "UI/UX Designer",
    "company": "Creative Studio",
    "location": "Nairobi, KE",
    "type": "Contract",
    "remote": true,
    "salary": { "min": 8000, "max": 12000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-16",
    "tags": ["Figma", "Adobe Creative Suite", "User Research", "Prototyping"],
    "description": "We need a talented designer to create intuitive user experiences and beautiful interfaces for our digital products.",
    "responsibilities": ["Create user interface designs", "Conduct user research", "Build interactive prototypes", "Collaborate with development team"],
    "requirements": ["3+ years UI/UX experience", "Proficiency in Figma", "Portfolio of web/mobile designs", "Understanding of user-centered design"],
    "benefits": ["Flexible schedule", "Remote work", "Creative freedom", "Competitive rate"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0004",
    "title": "DevOps Engineer",
    "company": "CloudTech Inc",
    "location": "Cairo, EG",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 7000, "max": 11000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-15",
    "tags": ["Docker", "Kubernetes", "AWS", "CI/CD"],
    "description": "Help us build and maintain robust infrastructure and deployment pipelines. You'll work with cutting-edge cloud technologies.",
    "responsibilities": ["Manage cloud infrastructure", "Automate deployment processes", "Monitor system performance", "Implement security best practices"],
    "requirements": ["3+ years DevOps experience", "Experience with AWS/Azure", "Knowledge of containerization", "Scripting skills (Python/Bash)"],
    "benefits": ["Remote work", "Health insurance", "Learning opportunities", "Modern tech stack"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0005",
    "title": "Data Scientist",
    "company": "Analytics Pro",
    "location": "Johannesburg, ZA",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 15000, "max": 22000, "currency": "ZAR", "period": "month" },
    "experience": "Senior",
    "postedAt": "2025-01-14",
    "tags": ["Python", "Machine Learning", "SQL", "Statistics"],
    "description": "Join our data team to extract insights from complex datasets and build predictive models that drive business decisions.",
    "responsibilities": ["Analyze large datasets", "Build ML models", "Create data visualizations", "Present findings to stakeholders"],
    "requirements": ["5+ years data science experience", "Strong Python skills", "ML/AI expertise", "Statistical analysis background"],
    "benefits": ["Competitive salary", "Health benefits", "Data science conferences", "Research opportunities"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0006",
    "title": "Full Stack Developer",
    "company": "Digital Dynamics",
    "location": "Casablanca, MA",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 8000, "max": 15000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-13",
    "tags": ["React", "Node.js", "TypeScript", "PostgreSQL"],
    "description": "Build end-to-end web applications with modern technologies. You'll work on both frontend and backend development.",
    "responsibilities": ["Develop frontend components", "Build backend APIs", "Database design", "Deploy applications"],
    "requirements": ["3+ years full-stack development", "React and Node.js experience", "Database knowledge", "Git workflow experience"],
    "benefits": ["Remote work", "Health coverage", "Learning budget", "Modern tech stack"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0007",
    "title": "Mobile Developer",
    "company": "MobileFirst",
    "location": "Addis Ababa, ET",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 6000, "max": 11000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-12",
    "tags": ["React Native", "iOS", "Android", "JavaScript"],
    "description": "Create cross-platform mobile applications that deliver exceptional user experiences across all devices.",
    "responsibilities": ["Develop mobile app features", "Optimize app performance", "Collaborate with design team", "Test on multiple devices"],
    "requirements": ["3+ years mobile development", "React Native experience", "iOS/Android knowledge", "JavaScript proficiency"],
    "benefits": ["Remote work", "Health insurance", "Mobile development tools", "App store experience"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0008",
    "title": "QA Engineer",
    "company": "QualityFirst",
    "location": "Tunis, TN",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 4000, "max": 7000, "currency": "USD", "period": "month" },
    "experience": "Junior",
    "postedAt": "2025-01-11",
    "tags": ["Testing", "Automation", "Selenium", "Jest"],
    "description": "Ensure our products meet the highest quality standards through comprehensive testing and automation.",
    "responsibilities": ["Write test cases", "Automate test scripts", "Perform manual testing", "Report and track bugs"],
    "requirements": ["1+ year QA experience", "Basic programming knowledge", "Understanding of testing principles", "Attention to detail"],
    "benefits": ["Health insurance", "Testing tools access", "Quality assurance training", "Career development"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0009",
    "title": "Product Manager",
    "company": "ProductPro",
    "location": "Dar es Salaam, TZ",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 9000, "max": 16000, "currency": "USD", "period": "month" },
    "experience": "Senior",
    "postedAt": "2025-01-10",
    "tags": ["Product Strategy", "Agile", "User Research", "Analytics"],
    "description": "Lead product development from concept to launch, working closely with engineering, design, and business teams.",
    "responsibilities": ["Define product roadmap", "Gather user requirements", "Prioritize features", "Coordinate cross-functional teams"],
    "requirements": ["5+ years product management", "Agile methodology experience", "Strong analytical skills", "Excellent communication"],
    "benefits": ["Competitive salary", "Health insurance", "Product management tools", "Leadership opportunities"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0010",
    "title": "Cybersecurity Analyst",
    "company": "SecurityNet",
    "location": "Algiers, DZ",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 7000, "max": 13000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-09",
    "tags": ["Security", "Network Analysis", "Incident Response", "Penetration Testing"],
    "description": "Protect our systems and data from cyber threats through proactive security measures and incident response.",
    "responsibilities": ["Monitor security systems", "Investigate security incidents", "Conduct vulnerability assessments", "Implement security measures"],
    "requirements": ["3+ years cybersecurity experience", "Security certifications preferred", "Network security knowledge", "Incident response experience"],
    "benefits": ["Competitive salary", "Security training", "Health benefits", "Professional development"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0011",
    "title": "React Developer",
    "company": "WebTech Solutions",
    "location": "Kampala, UG",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 5000, "max": 9000, "currency": "USD", "period": "month" },
    "experience": "Junior",
    "postedAt": "2025-01-08",
    "tags": ["React", "JavaScript", "CSS", "HTML"],
    "description": "Join our frontend team to build modern web applications using React and modern web technologies.",
    "responsibilities": ["Develop React components", "Implement responsive designs", "Write clean JavaScript code", "Collaborate with designers"],
    "requirements": ["1+ year React experience", "Strong JavaScript fundamentals", "CSS and HTML knowledge", "Git experience"],
    "benefits": ["Remote work", "Health insurance", "Learning budget", "Modern tech stack"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0012",
    "title": "Python Developer",
    "company": "CodeCraft",
    "location": "Rabat, MA",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 6000, "max": 12000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-07",
    "tags": ["Python", "Django", "Flask", "PostgreSQL"],
    "description": "Build robust backend services and APIs using Python frameworks. Work on scalable web applications.",
    "responsibilities": ["Develop Python backend services", "Design database schemas", "Write API endpoints", "Optimize performance"],
    "requirements": ["3+ years Python development", "Experience with Django/Flask", "Database design skills", "API development experience"],
    "benefits": ["Competitive salary", "Health coverage", "Python conferences", "Career growth"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0013",
    "title": "UX Researcher",
    "company": "UserInsights",
    "location": "Cape Town, ZA",
    "type": "Contract",
    "remote": true,
    "salary": { "min": 7000, "max": 11000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-06",
    "tags": ["User Research", "Usability Testing", "Data Analysis", "User Interviews"],
    "description": "Conduct user research to understand user needs and improve product experiences.",
    "responsibilities": ["Plan and conduct user research", "Analyze user behavior data", "Create research reports", "Present findings to stakeholders"],
    "requirements": ["3+ years UX research experience", "Research methodology knowledge", "Data analysis skills", "Strong communication"],
    "benefits": ["Remote work", "Flexible schedule", "Research tools access", "Professional development"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0014",
    "title": "Cloud Architect",
    "company": "CloudWorks",
    "location": "Dakar, SN",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 12000, "max": 20000, "currency": "USD", "period": "month" },
    "experience": "Senior",
    "postedAt": "2025-01-05",
    "tags": ["AWS", "Azure", "GCP", "Terraform", "Kubernetes"],
    "description": "Design and implement cloud infrastructure solutions for enterprise applications.",
    "responsibilities": ["Design cloud architecture", "Implement infrastructure as code", "Optimize cloud costs", "Ensure security compliance"],
    "requirements": ["7+ years cloud experience", "Expert in AWS/Azure/GCP", "Infrastructure as code skills", "Security knowledge"],
    "benefits": ["Competitive salary", "Health insurance", "Cloud certifications", "Remote work"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0015",
    "title": "Machine Learning Engineer",
    "company": "AI Innovations",
    "location": "Lagos, NG",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 10000, "max": 18000, "currency": "USD", "period": "month" },
    "experience": "Senior",
    "postedAt": "2025-01-04",
    "tags": ["Python", "TensorFlow", "PyTorch", "MLOps", "Docker"],
    "description": "Build and deploy machine learning models at scale. Work on cutting-edge AI applications.",
    "responsibilities": ["Develop ML models", "Implement MLOps pipelines", "Optimize model performance", "Deploy models to production"],
    "requirements": ["5+ years ML experience", "Expert in Python ML libraries", "MLOps experience", "Production deployment skills"],
    "benefits": ["Competitive salary", "Health benefits", "AI conferences", "Research opportunities"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0016",
    "title": "Frontend Team Lead",
    "company": "TechLeaders",
    "location": "Nairobi, KE",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 10000, "max": 16000, "currency": "USD", "period": "month" },
    "experience": "Senior",
    "postedAt": "2025-01-03",
    "tags": ["React", "Leadership", "Architecture", "Team Management"],
    "description": "Lead a team of frontend developers and drive technical decisions for our web applications.",
    "responsibilities": ["Lead frontend team", "Make technical decisions", "Code reviews", "Mentor developers"],
    "requirements": ["6+ years frontend development", "2+ years team leadership", "Strong technical skills", "Communication skills"],
    "benefits": ["Competitive salary", "Health insurance", "Leadership training", "Remote work"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0017",
    "title": "Backend Developer",
    "company": "ServerSide",
    "location": "Cairo, EG",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 6000, "max": 12000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-02",
    "tags": ["Java", "Spring Boot", "MySQL", "Microservices"],
    "description": "Build scalable backend services using Java and Spring Boot. Work on microservices architecture.",
    "responsibilities": ["Develop Java backend services", "Design APIs", "Database optimization", "Microservices development"],
    "requirements": ["3+ years Java development", "Spring Boot experience", "Database skills", "Microservices knowledge"],
    "benefits": ["Competitive salary", "Health coverage", "Java training", "Career growth"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0018",
    "title": "DevOps Engineer",
    "company": "InfraTech",
    "location": "Accra, GH",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 8000, "max": 14000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-01",
    "tags": ["Docker", "Kubernetes", "Jenkins", "Monitoring"],
    "description": "Manage our infrastructure and deployment pipelines. Ensure high availability and performance.",
    "responsibilities": ["Manage infrastructure", "Automate deployments", "Monitor systems", "Implement CI/CD"],
    "requirements": ["4+ years DevOps experience", "Containerization skills", "CI/CD experience", "Monitoring tools"],
    "benefits": ["Remote work", "Health insurance", "DevOps tools", "Learning opportunities"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0019",
    "title": "UI Designer",
    "company": "DesignHub",
    "location": "Johannesburg, ZA",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 5000, "max": 9000, "currency": "USD", "period": "month" },
    "experience": "Junior",
    "postedAt": "2024-12-31",
    "tags": ["UI Design", "Figma", "Adobe XD", "Design Systems"],
    "description": "Create beautiful and functional user interfaces for web and mobile applications.",
    "responsibilities": ["Design UI components", "Create design systems", "Collaborate with developers", "User testing"],
    "requirements": ["1+ year UI design experience", "Figma proficiency", "Design portfolio", "User-centered thinking"],
    "benefits": ["Health insurance", "Design tools access", "Design training", "Career development"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0020",
    "title": "Full Stack Developer",
    "company": "StackMasters",
    "location": "Casablanca, MA",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 7000, "max": 13000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2024-12-30",
    "tags": ["Vue.js", "Laravel", "MySQL", "Docker"],
    "description": "Build full-stack applications using Vue.js and Laravel. Work on modern web development.",
    "responsibilities": ["Develop frontend with Vue.js", "Build backend with Laravel", "Database design", "Deploy applications"],
    "requirements": ["3+ years full-stack development", "Vue.js and Laravel experience", "Database knowledge", "Docker experience"],
    "benefits": ["Remote work", "Health coverage", "Learning budget", "Modern tech stack"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0021",
    "title": "Data Engineer",
    "company": "DataFlow",
    "location": "Addis Ababa, ET",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 8000, "max": 15000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2024-12-29",
    "tags": ["Python", "Apache Spark", "Kafka", "Data Warehousing"],
    "description": "Build data pipelines and infrastructure for processing large-scale data.",
    "responsibilities": ["Design data pipelines", "Implement ETL processes", "Optimize data processing", "Maintain data infrastructure"],
    "requirements": ["4+ years data engineering", "Big data technologies", "Python programming", "Data warehousing"],
    "benefits": ["Remote work", "Health insurance", "Data tools access", "Professional development"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0022",
    "title": "Security Engineer",
    "company": "SecureNet",
    "location": "Tunis, TN",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 9000, "max": 16000, "currency": "USD", "period": "month" },
    "experience": "Senior",
    "postedAt": "2024-12-28",
    "tags": ["Cybersecurity", "Penetration Testing", "Security Tools", "Incident Response"],
    "description": "Protect our systems and data from security threats. Implement security best practices.",
    "responsibilities": ["Security assessments", "Penetration testing", "Security monitoring", "Incident response"],
    "requirements": ["5+ years security experience", "Penetration testing skills", "Security tools knowledge", "Incident response"],
    "benefits": ["Competitive salary", "Security training", "Health benefits", "Professional development"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0023",
    "title": "Product Designer",
    "company": "ProductCraft",
    "location": "Dar es Salaam, TZ",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 7000, "max": 12000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2024-12-27",
    "tags": ["Product Design", "User Experience", "Prototyping", "Design Thinking"],
    "description": "Design user experiences and product interfaces that solve real user problems.",
    "responsibilities": ["User research", "Create user flows", "Design interfaces", "Prototype solutions"],
    "requirements": ["4+ years product design", "UX/UI skills", "Prototyping tools", "Design thinking"],
    "benefits": ["Remote work", "Health insurance", "Design tools", "Creative freedom"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0024",
    "title": "Backend Team Lead",
    "company": "BackendLeaders",
    "location": "Algiers, DZ",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 12000, "max": 20000, "currency": "USD", "period": "month" },
    "experience": "Senior",
    "postedAt": "2024-12-26",
    "tags": ["Backend Development", "Leadership", "Architecture", "Team Management"],
    "description": "Lead our backend development team and drive technical decisions for scalable services.",
    "responsibilities": ["Lead backend team", "Architecture decisions", "Code reviews", "Mentor developers"],
    "requirements": ["7+ years backend development", "3+ years team leadership", "System design skills", "Communication skills"],
    "benefits": ["Competitive salary", "Health insurance", "Leadership training", "Remote work"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0025",
    "title": "Mobile App Developer",
    "company": "MobileWorks",
    "location": "Kampala, UG",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 5000, "max": 10000, "currency": "USD", "period": "month" },
    "experience": "Junior",
    "postedAt": "2024-12-25",
    "tags": ["Flutter", "Dart", "Mobile Development", "UI/UX"],
    "description": "Build cross-platform mobile applications using Flutter. Create beautiful mobile experiences.",
    "responsibilities": ["Develop Flutter apps", "Implement UI designs", "Test on devices", "App store deployment"],
    "requirements": ["1+ year Flutter experience", "Dart programming", "Mobile development", "UI/UX understanding"],
    "benefits": ["Health insurance", "Mobile tools access", "Flutter training", "Career growth"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0026",
    "title": "Frontend Developer",
    "company": "WebCraft",
    "location": "Rabat, MA",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 6000, "max": 11000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2024-12-24",
    "tags": ["Angular", "TypeScript", "SCSS", "RxJS"],
    "description": "Build modern web applications using Angular. Work on enterprise-level frontend development.",
    "responsibilities": ["Develop Angular components", "Implement state management", "Write unit tests", "Performance optimization"],
    "requirements": ["3+ years Angular experience", "TypeScript skills", "Testing experience", "Performance knowledge"],
    "benefits": ["Remote work", "Health coverage", "Angular training", "Modern tech stack"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0027",
    "title": "Data Analyst",
    "company": "DataInsights",
    "location": "Cape Town, ZA",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 6000, "max": 11000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2024-12-23",
    "tags": ["SQL", "Python", "Data Visualization", "Statistics"],
    "description": "Analyze data to provide insights that drive business decisions. Create reports and dashboards.",
    "responsibilities": ["Data analysis", "Create visualizations", "Write reports", "Present findings"],
    "requirements": ["3+ years data analysis", "SQL and Python skills", "Visualization tools", "Statistical knowledge"],
    "benefits": ["Competitive salary", "Health benefits", "Data tools access", "Professional development"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0028",
    "title": "Site Reliability Engineer",
    "company": "ReliabilityFirst",
    "location": "Dakar, SN",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 10000, "max": 18000, "currency": "USD", "period": "month" },
    "experience": "Senior",
    "postedAt": "2024-12-22",
    "tags": ["SRE", "Monitoring", "Automation", "Incident Management"],
    "description": "Ensure our systems are reliable, scalable, and performant. Implement SRE best practices.",
    "responsibilities": ["System reliability", "Performance monitoring", "Automation", "Incident response"],
    "requirements": ["5+ years SRE experience", "Monitoring tools", "Automation skills", "Incident management"],
    "benefits": ["Competitive salary", "Health insurance", "SRE training", "Remote work"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0029",
    "title": "Game Developer",
    "company": "GameStudio",
    "location": "Lagos, NG",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 8000, "max": 15000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2024-12-21",
    "tags": ["Unity", "C#", "Game Development", "3D Graphics"],
    "description": "Create engaging games using Unity. Work on game mechanics and user experience.",
    "responsibilities": ["Game development", "Implement game mechanics", "3D graphics", "Performance optimization"],
    "requirements": ["3+ years game development", "Unity experience", "C# programming", "3D graphics knowledge"],
    "benefits": ["Competitive salary", "Health benefits", "Game development tools", "Creative environment"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0030",
    "title": "Blockchain Developer",
    "company": "BlockchainTech",
    "location": "Nairobi, KE",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 9000, "max": 17000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2024-12-20",
    "tags": ["Solidity", "Ethereum", "Smart Contracts", "Web3"],
    "description": "Build decentralized applications and smart contracts on blockchain platforms.",
    "responsibilities": ["Smart contract development", "DApp development", "Blockchain integration", "Security auditing"],
    "requirements": ["3+ years blockchain development", "Solidity experience", "Ethereum knowledge", "Web3 understanding"],
    "benefits": ["Remote work", "Health insurance", "Blockchain tools", "Innovation focus"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0011",
    "title": "React Developer",
    "company": "WebTech Solutions",
    "location": "Kampala, UG",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 5000, "max": 9000, "currency": "USD", "period": "month" },
    "experience": "Junior",
    "postedAt": "2025-01-08",
    "tags": ["React", "JavaScript", "CSS", "HTML"],
    "description": "Join our frontend team to build modern web applications using React and modern web technologies.",
    "responsibilities": ["Develop React components", "Implement responsive designs", "Write clean JavaScript code", "Collaborate with designers"],
    "requirements": ["1+ year React experience", "Strong JavaScript fundamentals", "CSS and HTML knowledge", "Git experience"],
    "benefits": ["Remote work", "Health insurance", "Learning budget", "Modern tech stack"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0012",
    "title": "Python Developer",
    "company": "CodeCraft",
    "location": "Rabat, MA",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 6000, "max": 12000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-07",
    "tags": ["Python", "Django", "Flask", "PostgreSQL"],
    "description": "Build robust backend services and APIs using Python frameworks. Work on scalable web applications.",
    "responsibilities": ["Develop Python backend services", "Design database schemas", "Write API endpoints", "Optimize performance"],
    "requirements": ["3+ years Python development", "Experience with Django/Flask", "Database design skills", "API development experience"],
    "benefits": ["Competitive salary", "Health coverage", "Python conferences", "Career growth"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0013",
    "title": "UX Researcher",
    "company": "UserInsights",
    "location": "Cape Town, ZA",
    "type": "Contract",
    "remote": true,
    "salary": { "min": 7000, "max": 11000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-06",
    "tags": ["User Research", "Usability Testing", "Data Analysis", "User Interviews"],
    "description": "Conduct user research to understand user needs and improve product experiences.",
    "responsibilities": ["Plan and conduct user research", "Analyze user behavior data", "Create research reports", "Present findings to stakeholders"],
    "requirements": ["3+ years UX research experience", "Research methodology knowledge", "Data analysis skills", "Strong communication"],
    "benefits": ["Remote work", "Flexible schedule", "Research tools access", "Professional development"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0014",
    "title": "Cloud Architect",
    "company": "CloudWorks",
    "location": "Dakar, SN",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 12000, "max": 20000, "currency": "USD", "period": "month" },
    "experience": "Senior",
    "postedAt": "2025-01-05",
    "tags": ["AWS", "Azure", "GCP", "Terraform", "Kubernetes"],
    "description": "Design and implement cloud infrastructure solutions for enterprise applications.",
    "responsibilities": ["Design cloud architecture", "Implement infrastructure as code", "Optimize cloud costs", "Ensure security compliance"],
    "requirements": ["7+ years cloud experience", "Expert in AWS/Azure/GCP", "Infrastructure as code skills", "Security knowledge"],
    "benefits": ["Competitive salary", "Health insurance", "Cloud certifications", "Remote work"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0015",
    "title": "Machine Learning Engineer",
    "company": "AI Innovations",
    "location": "Lagos, NG",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 10000, "max": 18000, "currency": "USD", "period": "month" },
    "experience": "Senior",
    "postedAt": "2025-01-04",
    "tags": ["Python", "TensorFlow", "PyTorch", "MLOps", "Docker"],
    "description": "Build and deploy machine learning models at scale. Work on cutting-edge AI applications.",
    "responsibilities": ["Develop ML models", "Implement MLOps pipelines", "Optimize model performance", "Deploy models to production"],
    "requirements": ["5+ years ML experience", "Expert in Python ML libraries", "MLOps experience", "Production deployment skills"],
    "benefits": ["Competitive salary", "Health benefits", "AI conferences", "Research opportunities"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0016",
    "title": "Frontend Team Lead",
    "company": "TechLeaders",
    "location": "Nairobi, KE",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 10000, "max": 16000, "currency": "USD", "period": "month" },
    "experience": "Senior",
    "postedAt": "2025-01-03",
    "tags": ["React", "Leadership", "Architecture", "Team Management"],
    "description": "Lead a team of frontend developers and drive technical decisions for our web applications.",
    "responsibilities": ["Lead frontend team", "Make technical decisions", "Code reviews", "Mentor developers"],
    "requirements": ["6+ years frontend development", "2+ years team leadership", "Strong technical skills", "Communication skills"],
    "benefits": ["Competitive salary", "Health insurance", "Leadership training", "Remote work"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0017",
    "title": "Backend Developer",
    "company": "ServerSide",
    "location": "Cairo, EG",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 6000, "max": 12000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-02",
    "tags": ["Java", "Spring Boot", "MySQL", "Microservices"],
    "description": "Build scalable backend services using Java and Spring Boot. Work on microservices architecture.",
    "responsibilities": ["Develop Java backend services", "Design APIs", "Database optimization", "Microservices development"],
    "requirements": ["3+ years Java development", "Spring Boot experience", "Database skills", "Microservices knowledge"],
    "benefits": ["Competitive salary", "Health coverage", "Java training", "Career growth"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0018",
    "title": "DevOps Engineer",
    "company": "InfraTech",
    "location": "Accra, GH",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 8000, "max": 14000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2025-01-01",
    "tags": ["Docker", "Kubernetes", "Jenkins", "Monitoring"],
    "description": "Manage our infrastructure and deployment pipelines. Ensure high availability and performance.",
    "responsibilities": ["Manage infrastructure", "Automate deployments", "Monitor systems", "Implement CI/CD"],
    "requirements": ["4+ years DevOps experience", "Containerization skills", "CI/CD experience", "Monitoring tools"],
    "benefits": ["Remote work", "Health insurance", "DevOps tools", "Learning opportunities"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0019",
    "title": "UI Designer",
    "company": "DesignHub",
    "location": "Johannesburg, ZA",
    "type": "Full-time",
    "remote": false,
    "salary": { "min": 5000, "max": 9000, "currency": "USD", "period": "month" },
    "experience": "Junior",
    "postedAt": "2024-12-31",
    "tags": ["UI Design", "Figma", "Adobe XD", "Design Systems"],
    "description": "Create beautiful and functional user interfaces for web and mobile applications.",
    "responsibilities": ["Design UI components", "Create design systems", "Collaborate with developers", "User testing"],
    "requirements": ["1+ year UI design experience", "Figma proficiency", "Design portfolio", "User-centered thinking"],
    "benefits": ["Health insurance", "Design tools access", "Design training", "Career development"],
    "companyLogo": "/logo.svg"
  },
  {
    "id": "jb_0020",
    "title": "Full Stack Developer",
    "company": "StackMasters",
    "location": "Casablanca, MA",
    "type": "Full-time",
    "remote": true,
    "salary": { "min": 7000, "max": 13000, "currency": "USD", "period": "month" },
    "experience": "Mid",
    "postedAt": "2024-12-30",
    "tags": ["Vue.js", "Laravel", "MySQL", "Docker"],
    "description": "Build full-stack applications using Vue.js and Laravel. Work on modern web development.",
    "responsibilities": ["Develop frontend with Vue.js", "Build backend with Laravel", "Database design", "Deploy applications"],
    "requirements": ["3+ years full-stack development", "Vue.js and Laravel experience", "Database knowledge", "Docker experience"],
    "benefits": ["Remote work", "Health coverage", "Learning budget", "Modern tech stack"],
    "companyLogo": "/logo.svg"
  }
];

// Export the jobs data
export const jobsData = JOBS_DATA;

// Export a function to get all jobs
export function getAllJobs(): Job[] {
  return [...JOBS_DATA];
}

// Export a function to get a specific job by ID
export function getJobById(id: string): Job | undefined {
  return JOBS_DATA.find(job => job.id === id);
}

// Export a function to get jobs by company
export function getJobsByCompany(company: string): Job[] {
  return JOBS_DATA.filter(job => 
    job.company.toLowerCase().includes(company.toLowerCase())
  );
}

// Export a function to get jobs by location
export function getJobsByLocation(location: string): Job[] {
  return JOBS_DATA.filter(job => 
    job.location.toLowerCase().includes(location.toLowerCase())
  );
}

// Export a function to get remote jobs
export function getRemoteJobs(): Job[] {
  return JOBS_DATA.filter(job => job.remote);
}

// Export a function to get jobs by experience level
export function getJobsByExperience(experience: string): Job[] {
  return JOBS_DATA.filter(job => 
    job.experience.toLowerCase() === experience.toLowerCase()
  );
}
